### ISSUE TITLE
Using ScalablyTyped breaks scala-steward 

### ISSUE THREAD

**Issue by xerial** [xerial/scala-steward-repos#2]
https://github.com/xerial/scala-steward-repos/actions/runs/5524413185/jobs/10076683677
```
2023-07-11 20:09:29,224 INFO  ──────────── Steward xerial/scalajs-selenium ────────────
  2023-07-11 20:09:29,225 INFO  Check cache of xerial/scalajs-selenium
  2023-07-11 20:09:29,684 INFO  Clone xerial/scalajs-selenium
  2023-07-11 20:09:29,969 INFO  Refresh cache of xerial/scalajs-selenium
  2023-07-11 20:09:30,018 INFO  Get dependencies in . from sbt
  2023-07-11 20:13:28,882 ERROR Steward xerial/scalajs-selenium failed
  fs2.text$LineTooLongException: Max line size is 16384 but 24576 chars have been accumulated
  	at fs2.text$.$anonfun$linesImpl$1(text.scala:553)
  	at fs2.Pull$$anon$1.cont(Pull.scala:149)
  	at fs2.Pull$.fs2$Pull$$bindBindAux(Pull.scala:7[48](https://github.com/xerial/scala-steward-repos/actions/runs/5524413185/jobs/10076683677#step:7:50))
  	at fs2.Pull$BindBind.cont(Pull.scala:735)
  	at fs2.Pull$ContP.apply(Pull.scala:683)
  	at fs2.Pull$ContP.apply$(Pull.scala:683)
  	at fs2.Pull$Bind.apply(Pull.scala:691)
  	at fs2.Pull$Bind.apply(Pull.scala:691)
  	at fs2.Pull$UnconsRunR$1.$anonfun$out$2(Pull.scala:1019)
  	at fs2.Pull$.$anonfun$compile$2(Pull.scala:9[52](https://github.com/xerial/scala-steward-repos/actions/runs/5524413185/jobs/10076683677#step:7:54))
  	at get @ fs2.internal.Scope.openScope(Scope.scala:275)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:1[63](https://github.com/xerial/scala-steward-repos/actions/runs/5524413185/jobs/10076683677#step:7:65))
  	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
  	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
  	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
```

**Comment by xerial** [comment]
Related to https://github.com/scala-steward-org/scala-steward/pull/3125

**Comment by xerial** [comment]
Setting the max buffer size resolved this issue https://github.com/xerial/scala-steward-repos/commit/869591fee18494909dde9752ad301236d55f8b56
